name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    name: Server Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - name: mod
        run: go mod download
      - name: build
        run: go build
      - uses: actions/upload-artifact@v3
        with:
          name: booQ
          path: booQ
  lint:
    name: Server Lint
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - name: Install reviewdog
        run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - name: Install golangci-lint
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s --  -b $(go env GOPATH)/bin
      - name: golangci-lint
        run: golangci-lint run --out-format=line-number | reviewdog -f=golangci-lint -name=golangci-lint -reporter=github-check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Server Test
    runs-on: ubuntu-latest
    needs: [build]
    env:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: booq_test
    services:
      mysql:
        image: mariadb:10.6.4
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: booq_test
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - name: Setup DB
        run: go run .github/workflows/init.go
      - name: Run model tests
        run: go test . ./model -v -covermode=atomic -vet=off
      - name: Run router tests
        run: go test . ./router -v -covermode=atomic -vet=off
  spectral:
    name: OpenApi Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Spectral checks
        uses: stoplightio/spectral-action@v0.8.10
        with:
          file_glob: docs/swagger.yml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
